version: '3.3'
services:
  mysql:
    image: mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_USER: root
      MYSQL_ALLOW_EMPTY_PASSWORD: 'true'
      MYSQL_DATABASE: ad_service
    volumes:
      - ./db/volumes/mysql:/var/lib/mysql